# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.Club', verbose_name='俱乐部')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32, verbose_name='位置')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playerApp.PlayPosition', verbose_name='位置'),
        ),
    ]
