# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32, verbose_name='俱乐部名字')),
            ],
            options={
                'verbose_name': '俱乐部',
                'verbose_name_plural': '俱乐部',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=32, verbose_name='联赛名')),
            ],
            options={
                'verbose_name': '联赛',
                'verbose_name_plural': '联赛',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.DateTimeField(verbose_name='比赛时间')),
                ('z_goal', models.SmallIntegerField(verbose_name='主队进球')),
                ('k_goal', models.SmallIntegerField(verbose_name='客队进球')),
                ('p_result', models.SmallIntegerField(choices=[(0, '主队胜'), (1, '客队胜'), (2, '平局')], verbose_name='比赛结果')),
                ('l_circle', models.IntegerField(max_length=2, verbose_name='比赛轮数')),
                ('z_peilv', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='主赔率')),
                ('p_peilv', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='平赔率')),
                ('k_peilv', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='客赔率')),
                ('k_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_name_clubset', to='repository.Club', verbose_name='客队')),
                ('z_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_name_clubset', to='repository.Club', verbose_name='主队')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Club', verbose_name='俱乐部')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=32, verbose_name='位置')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.PlayPosition', verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='club',
            name='l_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.League', verbose_name='所属联赛'),
        ),
    ]
