# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='l_circle',
            field=models.IntegerField(verbose_name='比赛轮数'),
        ),
    ]
