# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, unique=True, verbose_name='网页')),
                ('type', models.CharField(choices=[(1, '球员'), (2, '俱乐部'), (3, '比赛')], max_length=5, verbose_name='网页类型')),
                ('flag', models.SmallIntegerField(verbose_name='是否已爬取')),
            ],
        ),
    ]
