# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=32, verbose_name='俱乐部名字')),
            ],
            options={
                'verbose_name': '俱乐部',
                'verbose_name_plural': '俱乐部',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=32, verbose_name='联赛名')),
            ],
            options={
                'verbose_name': '联赛',
                'verbose_name_plural': '联赛',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='l_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubApp.League', verbose_name='所属联赛'),
        ),
    ]
