# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='c_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='俱乐部名字'),
        ),
    ]
