# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_time', models.DateTimeField(verbose_name='比赛时间')),
                ('z_goal', models.SmallIntegerField(verbose_name='主队进球')),
                ('k_goal', models.SmallIntegerField(verbose_name='客队进球')),
                ('p_result', models.SmallIntegerField(choices=[('主队名字', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_name_clubset', to='clubApp.Club', verbose_name='主队')), ('客队名字', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_name_clubset', to='clubApp.Club', verbose_name='客队')), ('平了', 0)], verbose_name='比赛结果')),
                ('l_circle', models.SmallIntegerField(verbose_name='比赛轮数')),
                ('z_peilv', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='主赔率')),
                ('p_peilv', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='平赔率')),
                ('k_peilv', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='客赔率')),
                ('k_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k_name_clubset', to='clubApp.Club', verbose_name='客队')),
                ('z_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_name_clubset', to='clubApp.Club', verbose_name='主队')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
            },
        ),
    ]
