# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='k_peilv',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='客赔率'),
        ),
        migrations.AlterField(
            model_name='play',
            name='p_peilv',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='平赔率'),
        ),
        migrations.AlterField(
            model_name='play',
            name='p_result',
            field=models.SmallIntegerField(choices=[('主队名字', 2), ('客队名字', 1), ('平了', 0)], verbose_name='比赛结果'),
        ),
        migrations.AlterField(
            model_name='play',
            name='z_peilv',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='主赔率'),
        ),
    ]
